### Пример POST-запроса с заголовками
GET http://localhost:8000/statistics/excel/
#Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzIiwiZXhwZXJpZW5jZV9tb250aCI6NTcsInN1YiI6IjJkYTNiODQwLTc4MzMtNDRkYi05ZjNiLTY0NzliZmMyZjRhMyIsImFjdGl2ZSI6dHJ1ZSwic3VwZXJfdXNlciI6dHJ1ZSwiZXhwIjoxNzI5NDIxODE2LCJpYXQiOjE3Mjk0MjA5MTZ9.cB5h-9idVHlcMx6W63305EynSdBa_Er1dv7-HwKkMIdbgvD0BqPStqrDbxTv3dlz_CFDiHzsI2K1F5PrCuWDZOQJiWKczqAGKniIzMm5-cjeKBcYvxql58dSxQCzJ7Tx2oH-R4llrOI1A130Omz5jjwrqDPBV8iHecUjXpYsdeQ1bNNzIOC2D67uq55WMhI8NEiUlIMTQVg8krUdNUZ4B657RUcvbPYOoubQSkCUBy2NihJU40BbVM10MkdsnMDlplpDyfg-PxvaX2LxVmrH2k85j_STlRfSImguFP8PxBuoxI6f_zK_LltfTCu9geLwIRC7_GLA_JeFfKN17gyI0g
Content-Type: application/json

