"""Database creation

Revision ID: 03c31929d4f4
Revises: 
Create Date: 2024-10-14 18:55:49.649229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c31929d4f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benefits',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('update_at', sa.Date(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_benefits_uuid'), 'benefits', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('super_user', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('update_at', sa.Date(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.create_table('user_benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('benefits_uuid', sa.UUID(), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('update_at', sa.Date(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['benefits_uuid'], ['benefits.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_benefits_benefits_uuid'), 'user_benefits', ['benefits_uuid'], unique=False)
    op.create_index(op.f('ix_user_benefits_user_uuid'), 'user_benefits', ['user_uuid'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('update_at', sa.Date(), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid')
    )
    op.create_index(op.f('ix_user_profiles_user_uuid'), 'user_profiles', ['user_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_uuid'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_benefits_user_uuid'), table_name='user_benefits')
    op.drop_index(op.f('ix_user_benefits_benefits_uuid'), table_name='user_benefits')
    op.drop_table('user_benefits')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_benefits_uuid'), table_name='benefits')
    op.drop_table('benefits')
    # ### end Alembic commands ###
