"""Update constraint

Revision ID: 2cba038580a7
Revises: 5b0e29171def
Create Date: 2024-10-24 21:22:22.194095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cba038580a7'
down_revision: Union[str, None] = '5b0e29171def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_benefit', 'user_benefits', ['user_uuid', 'benefits_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_benefit', 'user_benefits', type_='unique')
    # ### end Alembic commands ###
