"""Add Category Photo

Revision ID: 2ec05478f8e6
Revises: 8caf9afd6ea9
Create Date: 2024-10-29 19:35:54.859470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec05478f8e6'
down_revision: Union[str, None] = '8caf9afd6ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('benefits_background_photo_fkey', 'benefits', type_='foreignkey')
    op.drop_column('benefits', 'background_photo')
    op.add_column('category', sa.Column('photo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'category', 'image', ['photo'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'photo')
    op.add_column('benefits', sa.Column('background_photo', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('benefits_background_photo_fkey', 'benefits', 'image', ['background_photo'], ['id'])
    # ### end Alembic commands ###
