"""Duration Benefit

Revision ID: 3602ac9cd407
Revises: 2ec05478f8e6
Create Date: 2024-10-30 16:50:06.515531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3602ac9cd407'
down_revision: Union[str, None] = '2ec05478f8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefits', sa.Column('duration_in_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benefits', 'duration_in_days')
    # ### end Alembic commands ###
