"""Add History

Revision ID: 4347741bc0cc
Revises: b7570a11dbdc
Create Date: 2024-11-20 18:57:34.158809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4347741bc0cc'
down_revision: Union[str, None] = 'b7570a11dbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('benefit_uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='Terminated', nullable=False),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ( 'Denied', 'Terminated')", name='check_status_history'),
    sa.ForeignKeyConstraint(['benefit_uuid'], ['benefits.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_benefits_benefit_uuid'), 'history_benefits', ['benefit_uuid'], unique=False)
    op.create_index(op.f('ix_history_benefits_user_uuid'), 'history_benefits', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_benefits_user_uuid'), table_name='history_benefits')
    op.drop_index(op.f('ix_history_benefits_benefit_uuid'), table_name='history_benefits')
    op.drop_table('history_benefits')
    # ### end Alembic commands ###
