"""FullHystoryApp2

Revision ID: 46bdd472b6d5
Revises: 749acf2f24c6
Create Date: 2024-11-26 22:19:35.050694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46bdd472b6d5'
down_revision: Union[str, None] = '749acf2f24c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_history_user_benefits', sa.Column('ucoin', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_history_user_benefits', 'ucoin')
    # ### end Alembic commands ###
