"""Create database

Revision ID: 5b0e29171def
Revises: 
Create Date: 2024-10-23 23:38:52.001766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0e29171def'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hash_password', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('super_user', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=False)
    op.create_table('benefits',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('background_photo', sa.Integer(), nullable=True),
    sa.Column('main_photo', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('experience_month', sa.Integer(), nullable=False),
    sa.Column('ucoin', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['background_photo'], ['image.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['main_photo'], ['image.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_benefits_uuid'), 'benefits', ['uuid'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('middlename', sa.String(), nullable=False),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid')
    )
    op.create_index(op.f('ix_user_profiles_user_uuid'), 'user_profiles', ['user_uuid'], unique=True)
    op.create_table('user_benefits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('benefits_uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='Pending', nullable=False),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('Approved', 'Denied', 'Pending')", name='check_status'),
    sa.ForeignKeyConstraint(['benefits_uuid'], ['benefits.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_benefits_benefits_uuid'), 'user_benefits', ['benefits_uuid'], unique=False)
    op.create_index(op.f('ix_user_benefits_user_uuid'), 'user_benefits', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_benefits_user_uuid'), table_name='user_benefits')
    op.drop_index(op.f('ix_user_benefits_benefits_uuid'), table_name='user_benefits')
    op.drop_table('user_benefits')
    op.drop_index(op.f('ix_user_profiles_user_uuid'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_benefits_uuid'), table_name='benefits')
    op.drop_table('benefits')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('image')
    op.drop_table('category')
    # ### end Alembic commands ###
