"""Logic verified

Revision ID: 77b84c7e8e9b
Revises: 4347741bc0cc
Create Date: 2024-11-22 01:47:42.705852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b84c7e8e9b'
down_revision: Union[str, None] = '4347741bc0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_codes',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('verification_code_expiration', sa.DateTime(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.Column('reset_code_expiration', sa.DateTime(), nullable=True),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid')
    )
    op.create_index(op.f('ix_user_codes_user_uuid'), 'user_codes', ['user_uuid'], unique=True)
    op.add_column('history_benefits', sa.Column('msg', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('history_benefits', 'msg')
    op.drop_index(op.f('ix_user_codes_user_uuid'), table_name='user_codes')
    op.drop_table('user_codes')
    # ### end Alembic commands ###
