"""UserProfile and Adap Period

Revision ID: 8caf9afd6ea9
Revises: 7884cb933b36
Create Date: 2024-10-27 17:14:23.952760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caf9afd6ea9'
down_revision: Union[str, None] = '7884cb933b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benefits', sa.Column('adap_period', sa.Boolean(), server_default='True', nullable=False))
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.add_column('user_profiles', sa.Column('legal_entity', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('job_title', sa.String(), nullable=True))
    op.alter_column('user_profiles', 'middlename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('adap_period', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'adap_period')
    op.alter_column('user_profiles', 'middlename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user_profiles', 'job_title')
    op.drop_column('user_profiles', 'legal_entity')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_column('benefits', 'adap_period')
    # ### end Alembic commands ###
