"""User Photo

Revision ID: 9c7d6a2c4f60
Revises: c991b848a81d
Create Date: 2024-11-23 17:54:59.810356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7d6a2c4f60'
down_revision: Union[str, None] = 'c991b848a81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_images',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('create_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_at', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.Column('delete_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('user_uuid')
    )
    op.create_index(op.f('ix_user_images_user_uuid'), 'user_images', ['user_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_images_user_uuid'), table_name='user_images')
    op.drop_table('user_images')
    # ### end Alembic commands ###
