"""password change

Revision ID: a3b1f37650ed
Revises: 9c7d6a2c4f60
Create Date: 2024-11-25 01:07:10.072694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b1f37650ed'
down_revision: Union[str, None] = '9c7d6a2c4f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_change_password', sa.Date(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('users', 'date_when_change_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_when_change_password', sa.DATE(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('users', 'date_change_password')
    # ### end Alembic commands ###
